services:
  db:
    image: postgres:latest
    volumes:
      - mtcg:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: marvin1
      POSTGRES_USER: marvin1
      POSTGRES_DB: mtcg
    ports:
      - "5433:5432"

volumes:
  mtcg: